// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a DIRECT (session) connection — the transaction-mode pooler
    // can't run DDL/advisory locks. The runtime app uses DATABASE_URL (which
    // should be the transaction pooler in production); migrations use DIRECT_URL,
    // falling back to DATABASE_URL where only one is set (e.g. CI's local DB).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
