// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Poolers (Supabase pgbouncer) can't run migrations — those go over the
    // DIRECT (unpooled) connection. The app runtime uses the pooled DATABASE_URL.
    // Locally there's no pooler, so DIRECT_URL falls back to DATABASE_URL.
    directUrl: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
